version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.5.1
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:8.0.21
        environment:
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: money_log_test
          MYSQL_ROOT_PASSWORD: mysqlRootPassword
    working_directory: ~/moneylog
    steps:
      - checkout
      - run:
          name: bundle install
          command: |
            gem install bundler
            RAILS_ENV=test bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: setup databases
          command: |
            RAILS_ENV=test ./bin/rails db:migrate
      - run:
          name: run rspec
          command: ./bin/rspec spec/feature

workflows:
  version: 2
  workflows:
    jobs:
      - test
