version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: 'mysqlRootPassword'
          TZ: "Asia/Tokyo"

      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: money_log_test
          MYSQL_ROOT_PASSWORD: 'mysqlRootPassword'
          TZ: "Asia/Tokyo"

    working_directory: ~/moneylog

    steps:
      - checkout
      - run:
          name: Wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Run bundle install
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            bundle install --jobs=4 --retry=3
      - run:
          name: Setup database
          command: |
            # RAILS_ENV=test ./bin/rails db:create
            # RAILS_ENV=test ./bin/rails db:schema:load
            # RAILS_ENV=test ./bin/rails db:migrate
      - run:
          name: Run RSpec
          command: |
            # RAILS_ENV=test bundle exec rspec spec/api/
            # RAILS_ENV=test bundle exec rspec spec/models/

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ######### production デプロイ時のビルド内容 #########
              echo "E2E master !"
              # RAILS_ENV=production bundle exec rspec spec/system/
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              ######### statign デプロイ時のビルド内容 #########
              echo "E2E staging !"
              # 1. Netlify: Reactをデプロイ & プロダクションビルド
              # 2. Heroku: Railsをデプロイ
                git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git staging
              # 3. RSpec: Largeテストを実行
                RAILS_ENV=staging bundle exec rspec spec/system/
            fi

workflows:
  version: 2
  workflows:
    jobs:
      - build
