version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby:2.7.1
        environment:
          RAILS_ENV: test
          BUNDLER_VERSION: 2.1.4
      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: money_log_test
          MYSQL_ROOT_PASSWORD: mysqlRootPassword
    working_directory: ~/moneylog
    steps:
      - checkout
      - run:
          name: wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: bundle install
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            RAILS_ENV=test bundle install --jobs=4 --retry=3
      - run:
          name: setup database
          command: |
            RAILS_ENV=test ./bin/rails db:schema:load
            RAILS_ENV=test ./bin/rails db:migrate
      - run:
          name: rspec
          command: |
            bundle exec rspec spec/features/

workflows:
  version: 2
  workflows:
    jobs:
      - test
