version: 2
jobs:
  build:
    working_directory: ~/moneylog

    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: development
          BUNDLER_VERSION: 2.1.4
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: 'mysqlRootPassword'
          TZ: "Asia/Tokyo"

      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: money_log_development
          MYSQL_ROOT_PASSWORD: 'mysqlRootPassword'
          TZ: "Asia/Tokyo"

    steps:
      - checkout
      - run:
          name: check shell
          command: echo $SHELL
      - run:
          name: check node
          command: node -v
      - run:
          name: install yarn
          command: |
            source ~/.bashrc
            curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.5
      - restore_cache:
          keys:
            - bundle-cache-{{ checksum "Gemfile.lock" }}
            - bundle-cache-
      - run:
          name: Run bundle install
          command: |
            gem install bundler
            bundle -v
            bundle config set path 'vendor/bundle'
            bundle install --clean --jobs=4 --retry=3
      - save_cache:
          key: bundle-cache-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Setup database
          command: |
            ./bin/rails db:migrate:reset
            ./bin/rails db:seed
      - run:
          name: Wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Small test Run RSpec
          command: |
            bundle exec rspec spec/api/
            bundle exec rspec spec/models/
            # bundle exec rspec spec/requests/
      # - run:
          # name: SMALL TEST Run Jest
          # command: |
            # Jestを実行
      - run:
          name: Medium or Large test Run Rspec 
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ######### production デプロイ時の内容 #########
              echo "E2E master !"
              # export RAILS_MASTER_KEY=${RAILS_PRODUCTION_KEY}
              # EC2デプロイ
              # S3デプロイ
              # RSpec実行
              # RAILS_ENV=production bundle exec rspec spec/system/
            elif [ "${CIRCLE_BRANCH}" == "staging" ]; then
              ######### statign デプロイ時の内容 #########
              echo "E2E staging !"
              # RAILS_MASTER_KEH のデフォルトの値がdevelopment.keyのため、staging.keyに変更
              export RAILS_MASTER_KEY=${RAILS_STAGING_KEY}
              # 1. Netlify: push時、Webpack自動プロダクションビルド
              # 2. Heroku: Railsデプロイ stagingブランチ ---push---> Herokuのmasterブランチへ反映
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git staging:master
              # 3. RSpec: Largeテストを実行
              RAILS_ENV=staging bundle exec rspec spec/system/
            else
              # 1 デーモンでプロセスを起動
              nohup yarn run start &
              ./bin/rails s -p 3001 -d
              # 2. RSpec: Mediumテストを実行
              bundle exec rspec spec/system/
            fi

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
