version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node-browsers
        environment:
          RAILS_ENV: development
          BUNDLER_VERSION: 2.1.4
          DB_HOST: 127.0.0.1
          DB_USERNAME: 'root'
          DB_PASSWORD: 'mysqlRootPassword'

      - image: circleci/mysql:8.0.21
        command: [--default-authentication-plugin=mysql_native_password]
        environment:
          MYSQL_DATABASE: money_log_development
          MYSQL_ROOT_PASSWORD: 'mysqlRootPassword'

    working_directory: ~/moneylog

    steps:
      - checkout
      - run:
          name: Wait for database
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Run bundle install
          command: |
            gem install bundler
            bundle config set path 'vendor/bundle'
            RAILS_ENV=test bundle install --jobs=4 --retry=3
      - run:
          name: Setup database
          command: |
            ./bin/rails db:create
            ./bin/rails db:schema:load
            ./bin/rails db:migrate
      - run:
          name: Run RSpec
          command: |

            bundle exec rspec spec/api/ && bundle exec rspec spec/models/

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # bundle exec rspec spec/system/
              echo "E2E test !"
            fi

workflows:
  version: 2
  workflows:
    jobs:
      - build
