@startuml
  title moneylog_ER_Diagram

  ' Relationship
  User --- Asset: owns >
  User ---o{ ExpenditureLog
  User ---o{ IncomeLog
  User ---o{ MonthlyExpenditure
  User ---o{ MonthlyIncome
  User ---o{ Tag

  MonthlyExpenditure ---o{ ExpenditureLog
  MonthlyIncome ---o{ IncomeLog

  IncomeLog ---o{ TagRelation
  ExpenditureLog ---o{ TagRelation

  Tag --o{ TagRelation

  class User {
    id
    name
    email
    password_digest
    created_at
    updated_at
  }
  class Asset {
    id
    user_id (foreign_key)
    amount
    created_at
    updated_at
  }
  class MonthlyExpenditure {
    id
    user_id (foreign_key)
    title
    amount
    content
    is_active
    will_create_at
    created_at
    updated_at
  }
  class MonthlyIncome {
    id
    user_id (foreign_key)
    title
    amount
    content
    is_active
    will_create_at
    created_at
    updated_at
  }
  class IncomeLog {
    id
    user_id (foreign_key)
    monthly_income_id (optional_foreign_key)
    amount
    title
    content
    earned_at
    created_at
    updated_at
  }
  class ExpenditureLog {
    id
    user_id (foreign_key)
    monthly_expenditure_id (optional_foreign_key)
    amount
    title
    content
    paid_at
    created_at
    updated_at
  }
  class TagRelation {
    id
    tag_id(foreign_key)
    expenditure_log_id(optional_foreign_key)
    income_log_id(optional_foreign_key)
  }
  class Tag {
    id
    user_id (foreign_key)
    name
    color
    description
    created_at
    updated_at
  }
@enduml
